// Mocks generated by Mockito 5.4.2 from annotations
// in nytimes/test/state/search/search_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:nytimes/modal/article.dart' as _i8;
import 'package:nytimes/modal/article_listing_content_type.dart' as _i9;
import 'package:nytimes/modal/document_article.dart' as _i7;
import 'package:nytimes/modal/failure_response.dart' as _i6;
import 'package:nytimes/service/article_store.dart' as _i4;
import 'package:nytimes/service/drift_db/data_model/article_data_model.dart'
    as _i11;
import 'package:nytimes/service/drift_db/data_model/document_article_data_model.dart'
    as _i12;
import 'package:nytimes/service/drift_db/drift_db.dart' as _i3;
import 'package:nytimes/service/drift_db_store.dart' as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDriftDB_1 extends _i1.SmartFake implements _i3.DriftDB {
  _FakeDriftDB_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ArticleStore].
///
/// See the documentation for Mockito's code generation for more information.
class MockArticleStore extends _i1.Mock implements _i4.ArticleStore {
  MockArticleStore() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Either<_i6.FailureResponse, List<_i7.DocumentArticle>>>
      searchDocumentArticles(
    String? keyword, {
    int? pageNumber = 1,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #searchDocumentArticles,
              [keyword],
              {#pageNumber: pageNumber},
            ),
            returnValue: _i5.Future<
                    _i2.Either<_i6.FailureResponse,
                        List<_i7.DocumentArticle>>>.value(
                _FakeEither_0<_i6.FailureResponse, List<_i7.DocumentArticle>>(
              this,
              Invocation.method(
                #searchDocumentArticles,
                [keyword],
                {#pageNumber: pageNumber},
              ),
            )),
          ) as _i5.Future<
              _i2.Either<_i6.FailureResponse, List<_i7.DocumentArticle>>>);
  @override
  _i5.Future<_i2.Either<_i6.FailureResponse, List<_i8.Article>>> fetchArticles(
          _i9.ArticleListingContentType? articleListingContentType) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchArticles,
          [articleListingContentType],
        ),
        returnValue: _i5
            .Future<_i2.Either<_i6.FailureResponse, List<_i8.Article>>>.value(
            _FakeEither_0<_i6.FailureResponse, List<_i8.Article>>(
          this,
          Invocation.method(
            #fetchArticles,
            [articleListingContentType],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.FailureResponse, List<_i8.Article>>>);
}

/// A class which mocks [DriftDBStore].
///
/// See the documentation for Mockito's code generation for more information.
class MockDriftDBStore extends _i1.Mock implements _i10.DriftDBStore {
  MockDriftDBStore() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.DriftDB get db => (super.noSuchMethod(
        Invocation.getter(#db),
        returnValue: _FakeDriftDB_1(
          this,
          Invocation.getter(#db),
        ),
      ) as _i3.DriftDB);
  @override
  _i5.Future<void> createOrUpdateArticle(
    _i8.Article? article,
    _i9.ArticleListingContentType? articleListingContentType,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createOrUpdateArticle,
          [
            article,
            articleListingContentType,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
  @override
  _i5.Future<List<_i11.ArticleDataModel>> fetchArticles(
          _i9.ArticleListingContentType? articleListingContentType) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchArticles,
          [articleListingContentType],
        ),
        returnValue: _i5.Future<List<_i11.ArticleDataModel>>.value(
            <_i11.ArticleDataModel>[]),
      ) as _i5.Future<List<_i11.ArticleDataModel>>);
  @override
  _i5.Future<void> createOrUpdateDocumentArticle(
          _i7.DocumentArticle? documentArticle) =>
      (super.noSuchMethod(
        Invocation.method(
          #createOrUpdateDocumentArticle,
          [documentArticle],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
  @override
  _i5.Future<List<_i12.DocumentArticleDataModel>> fetchDocumentArticles(
          String? keyword) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchDocumentArticles,
          [keyword],
        ),
        returnValue: _i5.Future<List<_i12.DocumentArticleDataModel>>.value(
            <_i12.DocumentArticleDataModel>[]),
      ) as _i5.Future<List<_i12.DocumentArticleDataModel>>);
}
