output-class: AppLocalization
arb-dir: lang/l10n
template-arb-file: intl_en.arb
output-localization-file: app_localizations.dart
synthetic-package: false # important, if you want to import the delegate in another package or app
output-dir: lib\generated