name: nytimes
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.18.1
  dartz: ^0.10.0
  dio: ^5.3.2
  app_settings: ^5.0.0
  flutter_bloc: ^8.1.2
  injectable: ^2.1.0
  get_it: ^7.2.0
  geolocator: ^10.0.0
  equatable: ^2.0.5
  connectivity_plus: ^3.0.3
  flutter_secure_storage: ^8.0.0
  drift: ^2.11.1
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  injectable_generator: ^2.1.4
  drift_dev: ^2.11.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
  fonts:
    - family: ReadexPro
      fonts:
        - asset: assets/fonts/readex_pro/ReadexPro-bold.ttf
        - asset: assets/fonts/readex_pro/ReadexPro-Regular.ttf
        - asset: assets/fonts/readex_pro/ReadexPro-Medium.ttf
    - family: Avenir
      fonts:
        - asset: assets/fonts/avenir/Avenir-Regular.ttf
        - weight: 400
        - asset: assets/fonts/avenir/Avenir-Black.ttf
        - weight: 600
        - asset: assets/fonts/avenir/Avenir-Heavy.ttf
        - weight: 700
